### PR TITLE
Add --nocleanup option

### PR DESCRIPTION
**Pull request by Tuebel**
Possible fix for #91.
I did not have the time to fully understand the extension architecture, so this fix might be too hacky.
The changes are small but help a lot when using the container for development.

### CODE REVIEW

**Comment by tfoote** [comment]
Thanks this looks good to add in the core, as the cleanup automation also is in the core. 

Before merging this could you add a quick unit test so make sure we have coverage of the CLI parsing. A dry_run test and asserting that the --rm is present and then not present with and without the option would be great.

**Comment by Tuebel** [comment]
Yes, I will do that probably towards the end of the week.

**Comment by Tuebel** [comment]
I have looked into it and there are probably a few more changes required to make the docker `cmd` testable.
Currently, the `run` function returns the subprocess `returncode` which makes assertions impossible. I see two possibilities:
1. Hijacking the print statements - brittle and no one will understand why a test is failing when a print statement is changed. But most of the existing code would stay untouched.
2. Create a new function `generate_docker_cmd` which returns the final `cmd` string. I would prefer this.

**Review by tfoote — APPROVED** [review]
Separating it out to a separate function is much cleaner. Thanks for doing that. This one too appears to conflict soon. I'll try to get to that shortly as well.

**Comment by chapulina** [comment]
Thanks for this! It would be great to get a release that provides this option.

**Pull request merged**
