### PR TITLE
Resolving issue #153 for hostname

### LINKED ISSUE #153: Option for hostname
First off, thank you so much for your work on this!
I have just a minor nitpick that I'm currently getting around with the also cool off-your-rocker package.
Currently, there is no option to set the hostname of the container.
That seems like a useful argument to have.

### PR DESCRIPTION
**Pull request by BabaYaga1221**
The code for the Hostname extension in rocker/extensions.py appears to be well-structured and follows the same pattern as the Name extension, effectively adding a --hostname argument and setting the hostname run arguments for the container. 
Fixes #153 
@tfoote

### CODE REVIEW

**Comment by tfoote** [comment]
Fixes #153 

FYI Please use the reference in the body so that github auto links it. 

Also please note that CI appear to have been broken today due to the actions being deprecated #225

**Comment by BabaYaga1221** [comment]
Thanks for the heads up. I'll make sure to include the reference in the body of my future pull requests. Also, I appreciate you letting me know about the issue with the CI. Do you know if there is a plan to resolve this soon?

**Comment by tfoote** [comment]
CI should be resolved now. Could you try rebasing your two PRs?

**Comment by BabaYaga1221** [comment]
Sure

**Pull request merged**
