### PR TITLE
Update nvidia_preamble.Dockerfile.em

### PR DESCRIPTION
**Pull request by pijaro**
This PR updates the Nvidia image version with the newer versions based on ubuntu 20.04 and 22.04.

This fixes some driver compatibility issues on the newest Ubuntu versions.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by tfoote — CHANGES_REQUESTED** [review]
Thanks this looks like this is an overdue update. However I think that this potentially breaks existing users on older platforms by forcing them to newer versions. We should make sure to have a path to have the older capabilities via an override.

So instead of just changing the template I would like to see the addition of a parameter to set `--nvidia-glvnd-version=XX.XX`   And if that's not set a policy `--nvidia-glvnd-policy=closest_lts` where we can do the logic to give the most recent LTS host similar to what you've implemented except allowing a little bit more interpolation to support not LTS versions that right now will get the 22.04 version even if it's on say 19.04. 

Then this version can be passed through to the template as a parameter.

**Comment by tfoote** [comment]
@pijaro Could you try #281 to verify it works for your use case?

**Comment by tfoote** [comment]
Closing this as superseded by #281

**Comment by pijaro** [comment]
@tfoote Thank you for the #281, it is indeed a better approach.

**Comment by tfoote** [comment]
Thanks for confirming it works for your case.

**Pull request closed without merging**
