### PR TITLE
Re-add Cuda Devel environment

### PR DESCRIPTION
**Pull request by woensug-choi**
Not sure how but the cuda support is removed at the latest main branch. It was merged before at https://github.com/osrf/rocker/pull/126. Now gone.. Adding back what is missing.

### CODE REVIEW

**Comment by tfoote** [comment]
Wow, thanks for catching that. That PR was old enough that it targeted the old development branch `master` instead of `main` which is where we develop now.  And we have automation to keep `master` mirroring `main` so I think the next merge to `main` mirrored and shadowed that merge.

**Comment by woensug-choi** [comment]
I can't miss it. I am using it every time.

**Comment by woensug-choi** [comment]
Maybe `--exclude test_cuda` option is required at `.github/workflows/basic-ci.yaml`

What was in the https://github.com/osrf/rocker/pull/126
```
        run: nosetests -s -v --with-coverage --cover-package rocker --exclude test_nvidia_glmark2 --exclude test_cuda
```

**Comment by tfoote** [comment]
We switched to pytest the tests need to be marked using the pytest method. I think I just did that in https://github.com/osrf/rocker/pull/210/commits/4e418f78115e18a71581c2b285a5c3e05ccfac42

**Review by tfoote — APPROVED** [review]
Thanks for the resubmission of #126 I did a few fixups to match the new testing and alphabetize the listing.

**Pull request merged**
